services:
  nginx:
    # Use the official Nginx image
    image: nginx:alpine
    # Map port 80 on the container to port 8080 on your host machine
    # You can change 8080 to any available port you prefer (e.g., 80, 8000)
    ports:
      - "8080:80"
    # Mount the local www/ directory to /var/www/html in the container
    volumes:
      - ./www:/var/www/html
      # Mount the custom Nginx configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # Link to the php-fpm service
    depends_on:
      - php
    # Restart policy: always restart unless stopped manually
    restart: unless-stopped
    networks:
      - app-network

  php:
    # Build the PHP-FPM image using our custom Dockerfile in the 'php' directory
    build:
      context: ./php
      dockerfile: Dockerfile
    # Mount the local www/ directory to /var/www/html in the container
    volumes:
      - ./www:/var/www/html
    # Restart policy: always restart unless stopped manually
    restart: unless-stopped
    networks:
      - app-network

networks:
  # Define a custom bridge network for services to communicate
  app-network:
    driver: bridge